theme = "blowfish"
baseURL = "https://aswinnr.com/blogs/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30
enableEmoji = true
buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[outputFormats.PostIndex]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]
