colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

defaultFeaturedImage = "img/default-cover.svg"
defaultBackgroundImage = "img/default-cover.svg"

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  cardView = true

[article]
  showDate = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showReadingTime = true
  showTableOfContents = true
  showHero = true
  heroStyle = "background"
  showTaxonomies = true
  showCategoriesInSecondaryColor = true
  showRelatedContent = true
  relatedContentLimit = 3
  sharingLinks = ["linkedin", "twitter", "reddit"]

[list]
  showCards = true
  showSummary = true
  showTableOfContents = false
